/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf --transform 
Files: scene.gltf [6.72KB] > /home/jerome/ClothesCustom/clothes/public/clothes1/scene-transformed.glb [1.67MB] (-24724%)
Author: deymar (https://sketchfab.com/deymar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-set-of-victorian-clothes-cfe0ad26828a42cebf49aea928ea8a15
Title: a set of Victorian clothes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Collar_FRONT_5309977} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
